### ISSUE TITLE
switch from detached head fails: Failed to delete ref refs/branch-wip/

### ISSUE THREAD

**Issue by abentley** [abentley/nit#32]
thread 'main' panicked at 'Failed to delete ref refs/branch-wip/', src/main.rs:597:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by abentley** [comment]
thread 'main' panicked at 'Failed to delete ref refs/branch-wip/', src/main.rs:597:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:435:5
   2: nit::create_branch_stash
             at /home/abentley/git/nit/src/main.rs:597:17
   3: <nit::Switch as nit::Runnable>::run
             at /home/abentley/git/nit/src/main.rs:97:43
   4: <nit::NativeCommand as nit::Runnable>::run
             at /home/abentley/git/nit/src/main.rs:215:1
   5: nit::main
             at /home/abentley/git/nit/src/main.rs:693:42
   6: core::ops::function::FnOnce::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
